[phases.setup]
nixPkgs = ["nodejs_22", "python3", "gnumake", "gcc", "pkg-config"]

[phases.install]
cmds = ["cd sabil-s-school-main && npm install"]

[phases.build]
cmds = ["cd sabil-s-school-main && npm run build"]

[start]
cmd = "cd sabil-s-school-main && node server/index.js"
